name: nf-dnds

channels:
    - conda-forge
    - bioconda

dependencies:
    - python==3.12
    - pip
    - conda-forge::jq
    - conda-forge::ncbi-datasets-cli
    - conda-forge::openssl
    - conda-forge::unzip
    - bioconda::diamond
    - bioconda::fasttree
    - bioconda::hyphy
    - bioconda::kaks-calculator
    - bioconda::mafft
    - bioconda::pal2nal
    - bioconda::proteinortho
    - bioconda::pseudofinder
    - bioconda::taxonkit
    - pip:
        - "carabiner-tools[pd,mpl]>=0.0.5.post3"
        - "numpy"
        - "scikit-learn"
        - 'multiqc>=1.21'
